### ISSUE TITLE
Rearranging the top of load run page

### ISSUE THREAD

**Issue by orchardman333** [sross07/crist-apples#11]
So I'd like to make a few edits to the top of the load page. As it stands now, when the bins are submitted, they all receive the truck driver and storage that are selected at the top of the page. I'd like that information at the top to be able to change for each bin.

For instance, I select a storage location. I scan one or more bins in and all those bins take that info. Then (without hitting submit) I can change the storage and the following bins that are scanned take the new storage room. I'd also like a date field and a boxes/bin field at the top with the same characteristic.

Please give me a call if this is unclear.

**Comment by orchardman333** [comment]
This is where we will set how many boxes will be split among the pickers

**Comment by sross07** [comment]
each barcode uses the currently select storage and truck driver at the time of the scan.  essentially changing the storage/truck driver scan to scan should do what you are looking for.  I agree that its not clear from the UI perspective that's whats happening ...I added that for each scan the storage and truck are now appended to the list (make sure you refresh your browser).  Does this make sense?

**Comment by orchardman333** [comment]
Oh wow I had no idea. I can't believe I didn't notice that feature before. I guess if you could just add options for boxes and date which default to today and 20, respectively, that would be fabulous

**Comment by sross07** [comment]
Added nr of boxes and defaulted to 20 (remember to refresh your browser). 
I will work on the date later tonight.

**Comment by orchardman333** [comment]
I'd also like a comment's box and a truck ID dropdown when you can get to it with the same per-bin characteristics

**Comment by sross07** [comment]
the comments and truck id are now stubbed out on the main page; need to finish wiring up the date, truck id ddl, and comments to the back end.

**Comment by sross07** [comment]
this is all wired up..
