### ISSUE TITLE
decodeBarcode choosing wrong pick ID

### ISSUE THREAD

**Issue by orchardman333** [sross07/crist-apples#13]
For some reason when the pick ID is 2 on the barcode, it gets decoded automatically as 1.
![image](https://cloud.githubusercontent.com/assets/20642233/17342648/32b256a2-58c8-11e6-9587-b33ab08f9cf1.png)

**Comment by sross07** [comment]
This is the code to decode the barcode:
  if (barcode.length == 17){
      values = {
        typeBarcode : 'bin',
        lengthBarCode: 17,
        strainId: barcode.substring(0, 2),
        varietyId: barcode.substring(2, 4),
        blockId: barcode.substring(4, 7),
        jobId: barcode.substring(7, 11),
        pickId: barcode.substring(12, 13),
        binId: barcode.substring(12, 17)
     }
  }
   else if (barcode.length ==15) {
      values = {
        typeBarcode : 'bin',
        lengthBarCode: 15,
        varietyId: barcode.substring(0, 2),
        blockId:  barcode.substring(2, 5),
        jobId:  barcode.substring(5, 9),
        pickId:  barcode.substring(9, 10),
        binId:  barcode.substring(10, 15)
        }
    }

it looks like something is still off?

**Comment by orchardman333** [comment]
Shoot. Sorry. This array index thing got me again. For length 17 barcodes:
pickId: barcode.substring(11, 12), Length 15 looks good

**Comment by sross07** [comment]
fixed
