### ISSUE TITLE
INSERT bin_table statements first

### ISSUE THREAD

**Issue by orchardman333** [sross07/crist-apples#16]
On most recent pull, the load_table and boxes_table INSERT statements are coming before the bin_table insertions, causing the load and boxes records to fail the fk constraints

**Comment by sross07** [comment]
For the boxes table, can we remove the FK constraint?

**Comment by orchardman333** [comment]
Hmm I'd prefer not to. Granted, I'm definitely not an expert. What is the cost to you if we keep the fk and benefit if we don't?

**Comment by sross07** [comment]
I'm not sure I know if there is is a negative, but given your time crunch, it seems like an easy solution to simply disable that FK.

**Comment by orchardman333** [comment]
I actually noticed it worked as expected today. I must have been doing something stupid last night
