### ISSUE TITLE
New form- inside crew time clock

### ISSUE THREAD

**Issue by orchardman333** [sross07/crist-apples#17]
Ready when you are.
[Inside time form.pdf](https://github.com/sross07/crist-apples/files/398265/Inside.time.form.pdf)

**Comment by sross07** [comment]
do you want this worked on next?

**Comment by orchardman333** [comment]
I would say it now takes equal priority as the other issues on the tracker.

**Comment by sross07** [comment]
First draft of this is available.. the datetimes are using "now()" as a concept so end users dont have to select a date time.. but i can easily make that a selection on the screen

Added two columns and dropped a primary key which i dont understand:
ALTER TABLE timecalc_table ADD column time_in  datetime null;
ALTER TABLE timecalc_table ADD column time_out datetime null;
alter table timecalc_table drop primary key;
