### ISSUE TITLE
every bin incorrectly receiving it's own load number

### ISSUE THREAD

**Issue by orchardman333** [sross07/crist-apples#19]
So when I hit submit, every bin receives it's own, unique load ID. I'd like all the bins submitted together to receive the same load ID.
![image](https://cloud.githubusercontent.com/assets/20642233/17366680/71d9fea6-595a-11e6-9bc3-83f176b0d88b.png)
For instance, bins 10001-3 were submitted at the same time but didn't receive the same load ID

**Comment by sross07** [comment]
To fix this, we will be creating a new table (use this script exactly): 
CREATE TABLE load_sequence (id INT NOT NULL);
INSERT INTO load_sequence VALUES (0);

**Comment by sross07** [comment]
this is fixed.  above script needs to be run on the database.
