### ISSUE TITLE
"Too many connections error"

### ISSUE THREAD

**Issue by orchardman333** [sross07/crist-apples#20]
So today I did a dry run to see the results. I scanned 45 bins only (no pickers) and only 2 bins made it to bin_table. When I checked the console, I this type of error:
![image](https://cloud.githubusercontent.com/assets/20642233/17450613/5ba455a6-5b2f-11e6-873c-9e59c629ba64.png)

**Comment by sross07** [comment]
i was not able to duplicate this but i implemented a fix for this to reduce # of connections
