### ISSUE TITLE
Reorder orchard run load form workflow

### ISSUE THREAD

**Issue by orchardman333** [sross07/crist-apples#24]
Given that we have a limited resource in screen space, I'd like consolidate the things that hardly ever change at the top and move the more-likely-to-change-per-bin down lower. Instead of this order:
![image](https://cloud.githubusercontent.com/assets/20642233/17453690/127ff7c6-5b4e-11e6-962f-31b4c507b778.png)
could we do the following order and have two columns of the dropdown options like this:
Truck Driver----------Truck ID
Storage---------------Date* 
nBoxes----------------Comments
--------Scan Barcode:-----------

*(I don't think this ever got put on but I'd like to be able to set the date and have it default to today.)

**Comment by sross07** [comment]
Added date..

**Comment by sross07** [comment]
reorganized screen into two columns
