### ISSUE TITLE
Load Review not populating fully and minor edits

### ISSUE THREAD

**Issue by orchardman333** [sross07/crist-apples#25]
This is what I scanned:
![image](https://cloud.githubusercontent.com/assets/20642233/17453837/55e9ed0c-5b51-11e6-8bce-f126f8c3e1b7.png)

This is what I got:
![image](https://cloud.githubusercontent.com/assets/20642233/17453838/732dc488-5b51-11e6-82b8-6ab2552ef1ea.png)

I'd also like the information on the load review page slightly rearranged to this order (let's eliminate the truck driver name):
Bin ID-Block-Variety-Strain-Storage-Boxes-Comments-Picker ID 1, ID 2...ID [number of pickers for that bin]
If it doesn't fit nicely in one row or if adding a variable number of picker ID's doesn't work well, let's do one row for the bin and an indented row for each picker in that bin.

**Comment by sross07** [comment]
this is done
