### ISSUE TITLE
Packout Form

### ISSUE THREAD

**Issue by orchardman333** [sross07/crist-apples#27]
Let's make a carbon copy of the Orchard Run Load and set the top of the forms to the following defaults:
Truck ID: Forklift
Storage: Pack

As for the bin_table, let's add a field on the form for packout ID for each bin.

Also, number of boxes and comments may be removed.

**Comment by sross07** [comment]
packout form = pack bin? correct?

**Comment by orchardman333** [comment]
Yes

**Comment by sross07** [comment]
This is setup on my side but I am waiting/wanting to resolve the connection issue before I commit this

**Comment by orchardman333** [comment]
Would you mind committing this please?

**Comment by sross07** [comment]
this has been released.. create new tickets for any issues
