### ISSUE TITLE
Scanned barcode lookup additions

### ISSUE THREAD

**Issue by orchardman333** [sross07/crist-apples#29]
After the block, variety and strain, I'd like to see the storage ID, date, number of boxes and comments in that order.
![image](https://cloud.githubusercontent.com/assets/20642233/17501637/7e0eb83a-5dae-11e6-96d0-7cad5252e006.png)

**Comment by orchardman333** [comment]
Also, when a picker employee ID is scanned, I'd like to see the picker's employee name, not the truck driver's.
For instance, this show's the driver's name rather than the picker's name.
![image](https://cloud.githubusercontent.com/assets/20642233/17518280/4d936982-5e15-11e6-9c5d-ef94ec9ff889.png)

**Comment by sross07** [comment]
The picker name is actually harder to do because it will require us to do a query back .. can I put that on hold until another time? 

The first part of this ticket is complete

**Comment by orchardman333** [comment]
Yeah that's totally fine. Maybe just strip all the display information off the employee scans other than the ID. Mostly I just didn't want to confuse the drivers filling out the form.
