### ISSUE TITLE
Still too many connections

### ISSUE THREAD

**Issue by orchardman333** [sross07/crist-apples#31]
I tried to enter only 16 bins on my phone and only 4 made it in...
![image](https://cloud.githubusercontent.com/assets/20642233/17526858/0eedf5cc-5e37-11e6-9d19-fdc1fd8ef151.png)

**Comment by orchardman333** [comment]
So I just entered a 21 bin load and everything went smooth sailing. Same location, same settings, etc. Not sure what was different.

**Comment by orchardman333** [comment]
It seems to be doing better as of now, 8/10/16 midday, but not perfect. I did a 23 bin load and only one of the load_table entries failed. All the bin_table entries were fine. Did you make the db pooling change?

**Comment by orchardman333** [comment]
28 bin load from my desktop computer. No go

**Comment by sross07** [comment]
can you try the 28  load?

**Comment by orchardman333** [comment]
Tried from my tablet (and cleared the records) and desktop and it seems to be a little different. I got all the bins in but only a few of the loads both times. (4 on my tablet, 10 on my desktop)

**Comment by sross07** [comment]
was there an error message?

**Comment by orchardman333** [comment]
just the usual. do you think this might possibly be a hardware limitation? I'm wondering because you are unable to replicate this scenario yet I'm seeing it routinely on loads > ~8 bins
![image](https://cloud.githubusercontent.com/assets/20642233/17609618/c46a4bde-6004-11e6-87eb-86aefa385917.png)

**Comment by sross07** [comment]
no i dont think its hardware, it could be windows / mysql and I been looking into that.  I think mysql has a default 100 connection out of the box configuration.

**Comment by orchardman333** [comment]
hmm that is a tad low. one thing is I'm not terrible concerned about lightning quick response. if it takes a second or two longer to avoid this error, I'm not against that.

**Comment by orchardman333** [comment]
Well, I think it looks promising. I tried 50 bins (= the biggest truck we have +2 bins) with no pickers from my desktop and it was totally successful.
Then, I tried 50 bins with two pickers each and got this:
![image](https://cloud.githubusercontent.com/assets/20642233/17643691/9554713a-613f-11e6-825e-a32ec11b63d7.png)
However, when I checked the db, only the first bin_table record made it in. No box or load_table records got in. I did a little more checking and something seems to be the matter when I add pickers to the load. I tried one bin with two pickers and got the same thing:
![image](https://cloud.githubusercontent.com/assets/20642233/17643901/a8956ac8-6145-11e6-8023-ec709573e140.png)

**Comment by sross07** [comment]
okay this should be fixed (connection.query.query) 
can you test again? 
i think we finally have this resolved..

**Comment by orchardman333** [comment]
Almost... so all the bin and load_table entries made it. 98 of the 100 boxes_tables entries made it. Here's the output:
[log.txt](https://github.com/sross07/crist-apples/files/416689/log.txt)

**Comment by sross07** [comment]
jedd try it now

**Comment by orchardman333** [comment]
So now it locked up once it got to the load_table inserts
![image](https://cloud.githubusercontent.com/assets/20642233/17649824/af4c23b8-620b-11e6-83e1-ccca789fd57a.png)

**Comment by orchardman333** [comment]
So very close! But I do see one more strange issue. Take a look at the review load pdf. I entered pickers 001 and 002 for every bin except a handful towards the end. But then look at sql executed. If you search for 003, you will see somehow an insert statement with picker 003 on bin 99901 found it's way in, even though I didn't type that employee ID in the whole form.
[deletes.pdf](https://github.com/sross07/crist-apples/files/417364/deletes.pdf)
[log.txt](https://github.com/sross07/crist-apples/files/417365/log.txt)

**Comment by orchardman333** [comment]
Actually, I just realized I may have had duplicates for bins 99900-99906. That may have caused the mayhem. But still strange

**Comment by orchardman333** [comment]
So I just tried another big load, making sure I didn't already have and primary keys in the db and it was perfect.

**Comment by sross07** [comment]
Okay I am going to close this issue..
