### ISSUE TITLE
more review load changes

### ISSUE THREAD

**Issue by orchardman333** [sross07/crist-apples#33]
At the top of the page, could I see the truck ID, truck driver name, date and time please? Also, the Block and Strain names are still not displaying correctly like the rest of the fields.

**Comment by sross07** [comment]
the date, truck id, truck name are finished.

The strain and block are being puilled from the strain table and block table respectively 
the sql is:
select `Strain Name` as name from strain_table where `Strain Id` =$strainId
-- strainId = the placement of the barcode

select `Block Name` as name from block_table where `Block Id` ='' 
-- blockId is blockId from barcode..

**Comment by sross07** [comment]
Can you let me know if the above sql matches what you expect?

**Comment by orchardman333** [comment]
I believe that is correct. It should pull the exact same way as the variety name does. Here's what I'm seeing:
![image](https://cloud.githubusercontent.com/assets/20642233/17664124/d87b4dd6-62bf-11e6-8292-1ac32676a169.png)

**Comment by sross07** [comment]
I can't duplicate this.  The block and strain are showing up for me on my side (with values that are available in the DB).  I added output to display the sql statement.  can you send me the sql or run it against your DB and let me know

**Comment by orchardman333** [comment]
So I ran it in my db client and looks good to me:
![image](https://cloud.githubusercontent.com/assets/20642233/17701811/45027612-6399-11e6-9417-edcba9e41158.png)
 The console looks like it had more trouble.
[log.txt](https://github.com/sross07/crist-apples/files/420432/log.txt)

**Comment by sross07** [comment]
resolved
