### ISSUE TITLE
Review Load heading

### ISSUE THREAD

**Issue by orchardman333** [sross07/crist-apples#34]
Just some minor edits.
The Truck ID is currently pulling the employee ID rather than the ID/name of the truck.
"Truck Name" should say "Truck Driver".
I'd also like the timestamp under the date.
![image](https://cloud.githubusercontent.com/assets/20642233/17703600/4c322200-63a0-11e6-9148-a872ed93021f.png)

**Comment by sross07** [comment]
With regards to date: Timestamp of what?  What does this date represent?  (Today? Now?)

**Comment by orchardman333** [comment]
Well the date you have on there currently is curdate() which refers to the date the load occurred. I'd like curtime() to appear underneath it to identify what time the bins were scanned in.

**Comment by sross07** [comment]
finished
