### ISSUE TITLE
Most recent commit

### ISSUE THREAD

**Issue by orchardman333** [sross07/crist-apples#35]
So somehow, the debugging changes you made somehow affected the bins making it into bin_table (I'm sure it was working on my last load yesterday. And if that wasn't a tough enough riddle for you, the bins did make it to load_table, which shouldn't happen because of the FK constraint... So bizarre

**Comment by sross07** [comment]
i will need more information.. do you have the log file output?

**Comment by orchardman333** [comment]
What made it to the db (I checked my server's db client as well and same thing):
![image](https://cloud.githubusercontent.com/assets/20642233/17706080/a41d6896-63a8-11e6-9aa1-9c2848c70f6c.png)
[no bin.txt](https://github.com/sross07/crist-apples/files/420699/no.bin.txt)

**Comment by sross07** [comment]
this should be resolved
