### ISSUE TITLE
Still losing the block and strain names on report

### ISSUE THREAD

**Issue by orchardman333** [sross07/crist-apples#38]
Form-bottom two bins have strains, top two do not (notice strain and block are no longer showing on the lookup bars):
![image](https://cloud.githubusercontent.com/assets/20642233/17857561/33ee4e26-6850-11e6-91ec-0b386b242d47.png)
Report:
![image](https://cloud.githubusercontent.com/assets/20642233/17857994/f794f7ca-6851-11e6-94d3-e6580c676ecf.png)
Data Tables (maybe an issue with the data being pulled? in this case the strain is Ld for Linda and h01 for H1):
![image](https://cloud.githubusercontent.com/assets/20642233/17858018/0c359e46-6852-11e6-8a54-ccbc72cda7bf.png)
![image](https://cloud.githubusercontent.com/assets/20642233/17858038/21002b52-6852-11e6-9097-0c0e6c5623cd.png)
Console (I added a few extra console.log statements):
![image](https://cloud.githubusercontent.com/assets/20642233/17858096/4d036f2a-6852-11e6-9ae9-0bcdff5e70b6.png)

**Comment by sross07** [comment]
that was a silly issue on my end .. try it now.
