### ISSUE TITLE
New Load ID for each load

### ISSUE THREAD

**Issue by orchardman333** [sross07/crist-apples#5]
Currently, all bins are entered into load_table under load ID == 1. I would like each load to have a unique number. For instance:

1. I drive a truck with 12 bins on my load. I scan them in. Those 12 bins have load ID == 1.
2. I complete another load with 14 bins onboard. These 14 bins have load ID == 2.
3. Another driver delivers & scans 48 bins. These 48 bins have load ID == 3.

So on and so forth...

**Comment by sross07** [comment]
This is completed..  confirmed fix as part of 7/31 patches
