### ISSUE TITLE
Picker employees and boxes on load form [highest priority]

### ISSUE THREAD

**Issue by orchardman333** [sross07/crist-apples#7]
Each bin needs to have the total boxes (aka bushels) for the bin_table and also the boxes picked per employee for the boxes_table

**Comment by orchardman333** [comment]
I'd like to be able to scan in order like the image below. The page could then match the employee numbers as the pickers to that bin and divide the "boxes.bin_table" by the number of pickers and store that info in boxes_table.
![image](https://cloud.githubusercontent.com/assets/20642233/17297159/852d6846-57d2-11e6-8c10-3ea6803a6d3c.png)
For example, emp 001 & 002 each get half of bin 10001's boxes and emp 003 gets all of bin 10002's boxes.

**Comment by sross07** [comment]
this is ready to be tested

**Comment by orchardman333** [comment]
I scanned one bin followed by two employee IDs. Here's what was consoled:
![image](https://cloud.githubusercontent.com/assets/20642233/17340901/2b920c8a-58c0-11e6-8f76-8d49e861def3.png)

What should have gone in was 2 statements instead of 3 (assuming this bin had a full 20 boxes):
INSERT INTO orchard run.boxes_table(10020,001,10,p090)
INSERT INTO orchard run.boxes_table(10020,002,10,p090)

Here's the table once again.
![image](https://cloud.githubusercontent.com/assets/20642233/17340928/561f5412-58c0-11e6-8afb-862dbffebe4e.png)

**Comment by orchardman333** [comment]
disregard that. i mistyped a bin tag. my bad

**Comment by sross07** [comment]
I am missing where we pick the boxes count from?  is it always 20?

**Comment by orchardman333** [comment]
Great job Scott! this looks really good. One thing I'd like to change is to round up each picker's boxes to the nearest hundredth of a decimal. So if 3 guys pick 20 bushels, each of them receives 6.67 boxes. And if 6 guys pick 20 boxes, they each receive 3.34 boxes.

I'm going to start a new ticket for your question as it is a little bit involved

**Comment by sross07** [comment]
rounding to nearest hundredth .. implemented..
