### ISSUE TITLE
Using bin barcode to lookup strain, variety and block names on load form

### ISSUE THREAD

**Issue by orchardman333** [sross07/crist-apples#8]

**Comment by sross07** [comment]
Variety, strain, and block names now display after you scan a barcode

**Comment by orchardman333** [comment]
I'm not seeing the variety, strain & block names still. Not sure what went wrong.
![image](https://cloud.githubusercontent.com/assets/20642233/17296656/521c1846-57d0-11e6-9d16-29573c67f104.png)
