### ISSUE TITLE
Bins no longer inserting into load_table

### ISSUE THREAD

**Issue by orchardman333** [sross07/crist-apples#9]
Does not appear that INSERT statement is being called.
![image](https://cloud.githubusercontent.com/assets/20642233/17298569/779c09e8-57d8-11e6-9ed4-74feb7650695.png)

**Comment by sross07** [comment]
I am going to leave this open but i think it is resolved per our work on 8/1

**Comment by orchardman333** [comment]
So when I tried to import multiple bins such as 10012-10017, there was a bin ID fk constraint failure. Not sure if it is related to what you found yesterday. All the insert statements look correct, but only two of the 6 bins made it to the db.
![image](https://cloud.githubusercontent.com/assets/20642233/17339066/3704e7e8-58b8-11e6-8eb6-fc1d30402a53.png)
[bin ID fk fail.txt](https://github.com/sross07/crist-apples/files/397746/bin.ID.fk.fail.txt)

**Comment by sross07** [comment]
fixed this as well
